package Daje::Document::Templates::Tools::Generate::Angular;
use Mojo::Base 'Daje::Document::Templates::Base', -base;
use v5.42;

# NAME
# ====
#
# Daje::Templates::Tools::Generate::Angular; - It creates Angular code
#
# SYNOPSIS
# ========
#
#     use Daje::Templates::Tools::Generate::Angular;
#
#     Provides a method for the template to be loaded into the data structure
#
#     sub length_default_calc($self) returns a sub for setting details in template.
#
#
# DESCRIPTION
# ===========
#
# Daje::Templates::Tools::Generate::Angular; is a module that retrieves data from a View
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

sub set_subs($self) {
    $self->subs('set_datatype');
}

sub set_datatype($datatype) {
    my $result = "string";
    if(uc($datatype) eq 'BIGINT') {
        $result = 'numeric';
    } elsif(uc($datatype) eq 'NUMERIC') {
        $result = 'numeric';
    } elsif(uc($datatype) eq 'BOOLEAN') {
        $result = 'boolean';
    } elsif(uc($datatype) eq 'MONEY') {
        $result = 'numeric';
    }

    return $result;
}
1;

__DATA__

@@ interface
// Autogenerated file [%- date_time %]
import{ ResponseBase } from 'daje-database';

export interface [%- class_name -%]Interface extends ResponseBase {
    [% project_name -%]_[%- table.table_name -%]_pkey:number,
    [%- FOREACH field IN fields -%]
    [%- IF field.foreign_key %]
    [% project_name -%]_[%- field.fieldname %]_fkey:number[% "," IF loop.last() == 0 %]
    [%- ELSE %]
    [% field.fieldname %]:[% set_datatype(field.datatype) %][% "," IF loop.last() == 0 %]
    [%- END -%]
    [% END %]
}

@@ component

// Autogenerated file [%- date_time %]
import {Component, OnInit, signal, ViewChild} from '@angular/core';
import {ConfirmationService, MessageService} from 'primeng/api';
import {Table, TableModule} from 'primeng/table';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ButtonModule} from 'primeng/button';
import {RippleModule} from 'primeng/ripple';
import {ToastModule} from 'primeng/toast';
import {ToolbarModule} from 'primeng/toolbar';
import {RatingModule} from 'primeng/rating';
import {InputTextModule} from 'primeng/inputtext';
import {TextareaModule} from 'primeng/textarea';
import {SelectModule} from 'primeng/select';
import {RadioButtonModule} from 'primeng/radiobutton';
import {InputNumberModule} from 'primeng/inputnumber';
import {DialogModule} from 'primeng/dialog';
import {TagModule} from 'primeng/tag';
import {InputIconModule} from 'primeng/inputicon';
import {IconFieldModule} from 'primeng/iconfield';
import { WorkflowService } from 'daje-workflow';
import { DatabaseService } from 'daje-database';
import { [%- class_name -%]Interface } from './[%- table.table_name -%].interface'

@Component({
  selector: 'p-[% project_name -%]-[%- table.table_name -%]',
  imports: [
        CommonModule,
        TableModule,
        FormsModule,
        ButtonModule,
        RippleModule,
        ToastModule,
        ToolbarModule,
        RatingModule,
        InputTextModule,
        TextareaModule,
        SelectModule,
        RadioButtonModule,
        InputNumberModule,
        DialogModule,
        TagModule,
        InputIconModule,
        IconFieldModule
  ],
  templateUrl: './[%table.table_name%].component.html',
  styleUrl: './[%table.table_name%].component.css',
  standalone: true,
})

export class [%- class_name -%]Component {
    payload:[%- class_name -%]Interface = {} as [%- class_name -%]Interface;
    selectedProducts:string = "";
    constructor(
        private workflow: WorkflowService,
        private database: DatabaseService,
    ) {}

    saveObject() {

    }

    cancelData() {

    }
    openNew() {

    }
    exportCSV() {}
    confirmDeleteSelected(){}
}

@@ component_html
<!-- Autogenerated file [%- date_time %] -->
<div>
    <div class="card">
        <p-toolbar styleClass="mb-6">
            <ng-template #start>
                <p-button label="New" icon="pi pi-plus" severity="secondary" class="mr-2" (onClick)="openNew()" />
                <p-button severity="secondary" label="Delete" icon="pi pi-trash" (onClick)="confirmDeleteSelected()" [disabled]="!selectedProducts || !selectedProducts.length" />
            </ng-template>

            <ng-template #end>
                <p-button label="Export" icon="pi pi-upload" severity="secondary" (onClick)="exportCSV()" />
            </ng-template>
        </p-toolbar>
    </div>
</div>
@@ css

/* [%- table.table_name -%].component.css */