package Daje::Document::Templates::Tools::Generate::Angular;
use Mojo::Base 'Daje::Document::Templates::Base', -base;
use v5.42;

# NAME
# ====
#
# Daje::Templates::Tools::Generate::Angular; - It creates Angular code
#
# SYNOPSIS
# ========
#
#     use Daje::Templates::Tools::Generate::Angular;
#
#     Provides a method for the template to be loaded into the data structure
#
#     sub length_default_calc($self) returns a sub for setting details in template.
#
#
# DESCRIPTION
# ===========
#
# Daje::Templates::Tools::Generate::Angular; is a module that retrieves data from a View
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

my $set_default = sub {
    my $datatype = $_[0];
    my $result = "''";
    if (uc($datatype) eq 'BIGINT') {
        $result = 0;
    }
    elsif (uc($datatype) eq 'NUMERIC') {
        $result = 0;
    }
    elsif (uc($datatype) eq 'BOOLEAN') {
        $result = 'false';
    }
    elsif (uc($datatype) eq 'MONEY') {
        $result = 0;
    }

    return $result;
};

my $set_datatype = sub {
    my $datatype = $_[0];
    my $result = "string";
    if (uc($datatype) eq 'BIGINT') {
        $result = 'number';
    }
    elsif (uc($datatype) eq 'NUMERIC') {
        $result = 'number';
    }
    elsif (uc($datatype) eq 'BOOLEAN') {
        $result = 'boolean';
    }
    elsif (uc($datatype) eq 'MONEY') {
        $result = 'number';
    }

    return $result;
};

my $set_filter_type = sub {
    my $datatype = $_[0];
    my $result = "text";
    if (uc($datatype) eq 'BIGINT') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'NUMERIC') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'BOOLEAN') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'MONEY') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'DATE') {
        $result = 'date';
    }
    return $result;
};

my $make_interface_name = sub {
    my $project = $_[0];
    my $table = $_[1];
    my $list = $_[2];
    $list = 0 unless defined $list;
    return ucfirst($project) . ucfirst($table) . "ListInterface" if ($list == 1);
    return ucfirst($project) . ucfirst($table) . "Interface";
};

my $ufirst = sub {
    return ucfirst($_[0]);
};

sub set_subs($self) {
    $self->insert_sub('set_datatype', $set_datatype);
    $self->insert_sub('make_interface_name', $make_interface_name);
    $self->insert_sub('ufirst', $ufirst);
    $self->insert_sub('set_default', $set_default);
    $self->insert_sub('set_filter_type', $set_filter_type);

}

1;

__DATA__
@@ endpoints
// Autogenerated file

export enum Endpoints {
[%- FOREACH table IN tables %]
	[% ufirst(project_name) -%][%- table.table_name -%] = '[%- table.table_name %]/',
    [%- FOREACH field IN table.fields %]
        [%- IF field.foreign_key && field.project == '' %]
    [% ufirst(project_name) -%][%- ufirst(table.table_name) -%][%- ufirst(field.fieldname) -%] = '[%- table.table_name -%]/[%- field.fieldname %]/',
        [%- ELSIF field.foreign_key && field.project != '' %]
    [% ufirst(field.project) -%][%- ufirst(table.table_name) -%][%- ufirst(field.fieldname) -%] = '[%- table.table_name -%]/[%- field.fieldname %]/',
        [%- END -%]
    [%- END -%]
[%- END %]
[%- FOREACH table IN tables %]
	[% ufirst(project_name) -%][%- ufirst(table.table_name) -%]ListAll = '[%- table.table_name -%]_list_all/',
    [%- FOREACH field IN table.fields %]
        [%- IF field.foreign_key && field.project == '' %]
    [% ufirst(project_name) -%][%- table.table_name -%]_[%- field.fieldname -%]List = '[%- table.table_name -%]/[%- field.fieldname -%]_list/',
        [%- ELSIF field.foreign_key && field.project != '' %]
    [% ufirst(field.project) -%][%- table.table_name -%]_[%- field.fieldname -%]List = '[%- table.table_name -%]/[%- field.fieldname -%]_list/',
        [%- END -%]
    [%- END -%]
[%- END %]
}


@@ interface
// Autogenerated file [%- date_time %]
import{ ResponseBase } from 'daje-database';

export interface [%- class_name -%]Interface extends ResponseBase {
    [% project_name -%]_[%- table.table_name -%]_pkey:number;
    [%- FOREACH field IN fields -%]
    [%- IF field.foreign_key && field.project == '' %]
    [% project_name -%]_[%- field.fieldname %]_fkey:number;
    [%- ELSIF field.foreign_key && field.project != '' %]
    [% field.project -%]_[%- field.fieldname %]_fkey:number;
    [%- ELSE %]
    [% field.fieldname %]:[% set_datatype(field.datatype) %];
    [%- END -%]
    [% END %]
}

export interface [%- class_name -%]ListInterface {
    [% project_name %]_[% table.table_name -%]_pkey: number;
    editnum: number;
    insby: string;
    insdatetime: string;
    modby: string;
    moddatetime: string;
[%- FOREACH field IN fields -%]
    [%- IF field.foreign_key && field.visible && field.dropfield && field.project == '' %]
    [% project_name -%]_[%- field.fieldname -%]_[%- field.dropfield %]: string;
    [% project_name %]_[% field.fieldname %]_fkey: number;
    [%- ELSIF field.foreign_key && field.visible && field.dropfield && field.project != '' %]
    [% field.project -%]_[%- field.fieldname -%]_[%- field.dropfield %]: string;
    [% field.project %]_[% field.fieldname %]_fkey: number;
    [%- ELSIF field.foreign_key && field.project != '' %]
    [% field.project %]_[% field.fieldname %]_fkey: number;
    [%- ELSIF field.foreign_key %]
    [% project_name %]_[% field.fieldname %]_fkey: number;
     [%- ELSE %]
    [% field.fieldname %]: [% set_datatype(field.datatype) %];
     [%- END -%]
     [% END %]
}

export class [%- class_name -%]Defaults {

    public defaults() {
        return {
                    [% project_name %]_[% table.table_name -%]_pkey: 0,
                    editnum: 0,
                    insby: '',
                    insdatetime: '',
                    modby: '',
                    moddatetime: '',
             [%- FOREACH field IN fields -%]
                [%- IF field.foreign_key && field.project == '' %]
                    [% project_name -%]_[%- field.fieldname %]_fkey: 0,
                [%- ELSIF field.foreign_key && field.project != '' %]
                    [% field.project -%]_[%- field.fieldname %]_fkey: 0,
                [%- ELSE %]
                    [% field.fieldname %]:[% set_default(field.datatype) %],
                [%- END -%]
            [% END %]
        };

    }
}
@@ component

// Autogenerated file [%- date_time %]
import {Component, OnInit, signal, ViewChild, WritableSignal, DestroyRef, inject, ElementRef} from '@angular/core';
import {ConfirmationService, MessageService} from 'primeng/api';
import {Table, TableModule} from 'primeng/table';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ButtonModule} from 'primeng/button';
import {RippleModule} from 'primeng/ripple';
import {ToastModule} from 'primeng/toast';
import {ToolbarModule} from 'primeng/toolbar';
import {RatingModule} from 'primeng/rating';
import {InputTextModule} from 'primeng/inputtext';
import {TextareaModule} from 'primeng/textarea';
import {SelectModule} from 'primeng/select';
import {RadioButtonModule} from 'primeng/radiobutton';
import {InputNumberModule} from 'primeng/inputnumber';
import {DialogModule} from 'primeng/dialog';
import {TagModule} from 'primeng/tag';
import {InputIconModule} from 'primeng/inputicon';
import {IconFieldModule} from 'primeng/iconfield';
import { FloatLabel } from 'primeng/floatlabel';
import { DatePickerModule } from 'primeng/datepicker';
import { WorkflowService,  } from 'daje-workflow';
import { DatabaseService } from 'daje-database';
import { CommonComponent } from 'daje-common';
import { CheckboxModule } from 'primeng/checkbox';
import { UserLoginService } from 'daje-login';
import { TranslationsService } from 'daje-languages';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { TooltipModule } from 'primeng/tooltip';
import { MultiSelectModule } from 'primeng/multiselect';
import { Router } from '@angular/router';

import { [%- class_name -%]Interface, [%- class_name -%]ListInterface, [%- class_name -%]Defaults } from './[%- table.table_name -%].interface'
[%- FOREACH field IN fields -%]
        [%- IF field.foreign_key && field.visible && field.project == '' %]
import { [%- make_interface_name(project_name, field.fieldname, 1) -%] } from '../[%- field.fieldname -%]/[%- field.fieldname -%].interface';
        [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
import { [%- make_interface_name(field.project, field.fieldname, 1) -%] } from '../[%- field.fieldname -%]/[%- field.fieldname -%].interface';
        [%- END -%]
    [% END %]
import { Endpoints } from '../[%- project_name -%]_endpoints/[%- project_name -%].endpoints';
import { ImportWizardService } from 'daje-import';
import { AuthoritiesService } from 'daje-authorities';

interface Column {
    field: string;
    header: string;
    customExportHeader?: string;
    order: number;
    datatype: string;
    datatype_org: string;
    import_field: string;
}

interface ExportColumn {
    title: string;
    dataKey: string;
}

@Component({
  selector: 'p-[% project_name -%]-[%- table.table_name -%]',
  imports: [
        CommonModule,
        TableModule,
        FormsModule,
        ButtonModule,
        RippleModule,
        ToastModule,
        ToolbarModule,
        RatingModule,
        InputTextModule,
        TextareaModule,
        SelectModule,
        RadioButtonModule,
        InputNumberModule,
        DialogModule,
        TagModule,
        InputIconModule,
        IconFieldModule,
        CheckboxModule,
        FloatLabel,
        DatePickerModule,
        TooltipModule,
        MultiSelectModule
  ],
  templateUrl: './[%table.table_name%].component.html',
  styleUrl: './[%table.table_name%].component.css',
  standalone: true,
})

export class [%- class_name -%]Component extends CommonComponent {
    [% class_name -%]def: [%- class_name -%]Defaults = new [%- class_name -%]Defaults();
    detailDialog: WritableSignal<boolean> = signal<boolean>(false);
    deleteDialog: WritableSignal<boolean> = signal<boolean>(false);
    payload:WritableSignal<[%- class_name -%]Interface> = signal<[%- class_name -%]Interface>(this.[%- class_name -%]def.defaults());
    payload_list = [] as [%- class_name -%]ListInterface[];
    payload_detail = {} as [%- class_name -%]ListInterface;
    selectedPayloads:[%- class_name -%]Interface = {} as [%- class_name -%]Interface;
    submitted:boolean = false;
    [%- FOREACH field IN fields %]
    [%- IF field.foreign_key && field.visible && field.project == '' %]
    selected_[%- project_name -%]_[%- field.fieldname -%]: any = {};
    [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
    selected_[%- field.project -%]_[%- field.fieldname -%]: any = {};
    [%- END %]
[%- END %]
    [%- FOREACH field IN fields -%]
        [%- IF field.foreign_key && field.visible && field.project == '' %]
    selected_[%- field.dropfield -%]: string = "";
    [% project_name -%]_[%- field.fieldname -%]_list = [] as [% make_interface_name(project_name, field.fieldname, 1) %][];
        [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
    selected_[%- field.dropfield -%]: string = "";
    [% field.project -%]_[%- field.fieldname -%]_list = [] as [% make_interface_name(field.project, field.fieldname, 1) %][];
        [%- END -%]
    [% END %]
    tableLoading: WritableSignal<boolean> = signal<boolean>(false);
    userSettingsDialog: WritableSignal<boolean> = signal<boolean>(false);


    private destroyRef = inject(DestroyRef);

    @ViewChild('dt') dt!: Table;
    exportColumns!: ExportColumn[];
    cols!: Column[];
    selectedColumns!: Column[];
    @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;

    constructor(
        private workflow: WorkflowService,
        private database: DatabaseService,
        public translations: TranslationsService,
        private importer: ImportWizardService,
        private router: Router,
        private authorities: AuthoritiesService,
    ) {
        super();
        this.database.set_endpoints(Endpoints);

[%- FOREACH field IN fields -%]
    [%- IF field.foreign_key && field.visible && field.project == '' -%]
        this.database.load_all_records('[%- field.fieldname -%]_list_all', false).pipe(takeUntilDestroyed()).subscribe((response: [% make_interface_name(project_name, field.fieldname, 1) %][]) => {
            this.[% project_name -%]_[%- field.fieldname -%]_list = response;
        });
    [%- ELSIF field.foreign_key && field.visible && field.project != '' -%]
        this.database.load_all_records('[%- field.fieldname -%]_list_all', false).pipe(takeUntilDestroyed()).subscribe((response: [% make_interface_name(field.project, field.fieldname, 1) %][]) => {
            this.[% field.project -%]_[%- field.fieldname -%]_list = response;
        });
    [% END -%]
[% END -%]

        this.cols = this.buildCols().sort((a,b) => a.order - b.order);
        this.selectedColumns = this.cols;
        this.exportColumns = this.cols.map((col) => ({
            title: col.header,
            dataKey: col.field
        }));
    }

    has_authority(plugin: string, func: string, permission: string): boolean {
        return (this.authorities.has_authority(plugin, func, permission));
    }

    exportCSV() {
        this.dt.exportCSV();
    }

    showImportData() {
        this.importer.setup('[%- project_name -%]', '[%- table.table_name -%]', this.cols);
        this.router.navigate(['/home/[% project_name -%]/import/csv']);
    }

    hideImportData() {
        this.router.navigate(['/home/[% project_name -%]/list']);
    }

    ngOnInit() {
        this.loadData();
    }

    loadData() {
        this.tableLoading.set(true)
        this.database.load_all_records('[% ufirst(project_name) -%][%- ufirst(table.table_name) -%]ListAll').pipe(takeUntilDestroyed(this.destroyRef)).subscribe((response: [%- class_name -%]ListInterface[]) => {
            this.payload_list = response;
            this.tableLoading.set(false)
    [%- FOREACH field IN fields %]
        [%- IF field.datatype == 'BOOLEAN'  %]
            if(this.payload().[%- field.fieldname -%]) this.payload().[%- field.fieldname -%] = true;
        [%- END %]
    [%- END %]
        });


    }

    saveObject() {
        this.submitted = true;
        if(!this.payload().[%- project_name -%]_[%- table.table_name -%]_pkey) this.payload().[%- project_name -%]_[%- table.table_name -%]_pkey = 0;
[%- FOREACH field IN fields %]
    [%- IF field.foreign_key && field.visible && field.project == '' %]
        this.payload().[%- project_name -%]_[%- field.fieldname -%]_fkey = this.selected_[%- project_name -%]_[%- field.fieldname -%].[%- project_name -%]_[%- field.fieldname -%]_pkey;
    [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
        this.payload().[%- field.project -%]_[%- field.fieldname -%]_fkey = this.selected_[%- field.project -%]_[%- field.fieldname -%].[%- field.project -%]_[%- field.fieldname -%]_pkey;
    [%- END %]
[%- END %]

[%- FOREACH field IN fields %]
    [%- IF field.datatype == 'BOOLEAN' %]
        if(!this.payload().[%- field.fieldname -%]) this.payload().[%- field.fieldname -%] = false;
    [%- END %]
    [%- IF field.fieldname == 'workflow' && field.foreign_key %]
        if(!this.payload().[%- project_name -%]_[%- field.fieldname -%]_fkey) this.payload().[%- project_name -%]_[%- field.fieldname -%]_fkey = 0;
    [%- END %]
[%- END %]

        this.workflow.callWorkflow(
    [%- IF table.workflow %]
           '[% project_name -%]_[%- table.workflow -%]', 'save_[%- project_name -%]_[%- table.table_name -%]', this.payload()
    [%- ELSE %]
           '[% project_name -%]_[%- project_name -%]', 'save_[%- project_name -%]_[%- table.table_name -%]', this.payload()
    [% END %]
        );

        this.loadData();
        let _payload = this.payload_list;
        if (this.payload().[%- project_name -%]_[%- table.table_name -%]_pkey > 0) {
            this.selectedPayloads  = _payload[this.findIndexBypKey(this.payload().[%- project_name -%]_[%- table.table_name -%]_pkey)];
        } else {
    [%- FOREACH field IN fields %]
        [%- IF field.unique %]
            this.selectedPayloads  = _payload[this.findIndexBy_[%- field.fieldname %](this.payload().[%- field.fieldname -%])];
        [%- END %]
    [%- END %]

        }

        this.detailDialog.set(false);
    }

    onGlobalFilter(table: Table, event: Event) {
        table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
    }

    openNew() {
        this.payload.set(this.[%- class_name -%]def.defaults());
        this.submitted = false;
        this.detailDialog.set(true);
[%- FOREACH field IN fields %]
    [%- IF field.foreign_key && field.visible && field.project == '' %]
        this.payload().[%- project_name -%]_[%- field.fieldname -%]_fkey = 0;
    [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
        this.payload().[%- field.project -%]_[%- field.fieldname -%]_fkey = 0;
    [%- END %]
[%- END %]
    }

    findIndexBypKey(pKey: number = 0): number {
        let index = -1;
        for (let i = 0; i < this.payload_list.length; i++) {
            if (this.payload_list[i].[%- project_name -%]_[%- table.table_name -%]_pkey === pKey) {
                index = i;
                break;
            }
        }
        return index;
    }
[%- FOREACH field IN fields %]
    [%- IF field.unique %]
    findIndexBy_[%- field.fieldname %]([%- field.fieldname %]: string = ''): number {
        let index = -1;
        for (let i = 0; i < this.payload_list.length; i++) {
            if (this.payload_list[i].[%- field.fieldname %] === [%- field.fieldname %]) {
                index = i;
                break;
            }
        }
        return index;
    }
    [%- END %]
[%- END %]

[%- FOREACH field IN fields %]
    [%- IF field.foreign_key && field.visible && field.project == '' %]
    findIndexBy_[%- field.fieldname %]([% project_name -%]_[%- field.fieldname %]_fkey: number = 0): number {
        let index = -1;
        if (this.[% project_name -%]_[%- field.fieldname -%]_list,length > 0) {
            for (let i = 0; i < this.[% project_name -%]_[%- field.fieldname -%]_list.length; i++) {
                if (this.[% project_name -%]_[%- field.fieldname -%]_list[i].[% project_name -%]_[%- field.fieldname %]_pkey === [% project_name -%]_[%- field.fieldname %]_fkey) {
                    index = i;
                    break;
                }
            }
        }
        return index;
    }

    [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
    findIndexBy_[%- field.fieldname %]([% field.project -%]_[%- field.fieldname %]_fkey: number = 0): number {
        let index = -1;
        if (this.[% field.project -%]_[%- field.fieldname -%]_list.length > 0) {
            for (let i = 0; i < this.[% field.project -%]_[%- field.fieldname -%]_list.length; i++) {
                if (this.[% field.project -%]_[%- field.fieldname -%]_list[i].[% field.project -%]_[%- field.fieldname %]_pkey === [% field.project -%]_[%- field.fieldname %]_fkey) {
                    index = i;
                    break;
                }
            }
        }
        return index;
    }
    [%- END %]
[%- END %]
    editSelected(payload: [%- class_name -%]Interface) {
        this.database.load_record('[% ufirst(project_name) -%][%- table.table_name -%]', payload.[% project_name -%]_[%- table.table_name -%]_pkey).pipe(takeUntilDestroyed(this.destroyRef)).subscribe((response: [%- class_name -%]Interface)=> {
            this.payload.set(response)
     [%- FOREACH field IN fields %]
        [%- IF field.datatype == 'BOOLEAN'  %]
            if(this.payload().[%- field.fieldname -%]) this.payload().[%- field.fieldname -%] = true;
        [%- END %]
    [%- END %]
     [%- FOREACH field IN fields -%]
        [%- IF field.foreign_key && field.visible && field.project == '' %]
            this.selected_[%- project_name -%]_[%- field.fieldname -%] = this.[% project_name -%]_[%- field.fieldname -%]_list[this.findIndexBy_[%- field.fieldname %](payload.[% project_name -%]_[%- field.fieldname %]_fkey)];
        [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
            this.selected_[%- field.project -%]_[%- field.fieldname -%] = this.[% field.project -%]_[%- field.fieldname -%]_list[this.findIndexBy_[%- field.fieldname %](payload.[% field.project -%]_[%- field.fieldname %]_fkey)];
        [%- END -%]
    [% END %]
            this.detailDialog.set(true);
        });
    }

    deleteSelected(payload: [%- class_name -%]Interface) {
        this.payload.set({ ...payload });
[%- FOREACH field IN fields %]
    [%- IF field.fieldname == 'workflow' && field.foreign_key %]
        this.workflow.setWorkflowpKey(this.payload().[%- project_name -%]_[%- field.fieldname -%]_fkey);
    [%- END %]
[%- END %]
        this.workflow.callWorkflow(
    [%- IF table.workflow %]
            '[% project_name -%]_[%- table.workflow -%]', 'delete_[%- project_name -%]_[%- table.table_name -%]', this.payload()
    [%- ELSE %]
            '[% project_name -%]_[%- project_name -%]', 'delete_[%- project_name -%]_[%- table.table_name -%]', this.payload()
    [% END %]
        );
        this.deleteDialog.set(false);
        this.loadData();
    }

    confirmDeleteSelected(payload: [%- class_name -%]Interface){
        this.payload.set({ ...payload });
        this.deleteDialog.set(true);
    }

    confirmDeleteSelectedLines() {}

    hideDialog() {
        this.detailDialog.set(false);
    }
    userConfig(project: string, table: string, type: string) {
        this.userSettingsDialog.set(true);
    }
    reorderColumns(event: any) {
        event = event;
    }
    resizeColumns(event: any) {
        event = event;
    }
    hideUserSettingsDialog() {
        this.userSettingsDialog.set(false);
    }
    saveUserSettingsObject() {

    }
    triggerFileUpload() {
        this.fileInput.nativeElement.click();
    }

    handleFileUpload(event: Event) {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];
        if (file) {
            //this.formStateService.updateField('profilePhoto', file);
            // this.formStateService.updateField('profilePhotoUrl', URL.createObjectURL(file));
        }
    }
    buildCols() {
        return [
        [%- FOREACH field IN fields %]
            [%- IF field.foreign_key && field.visible && field.dropfield && field.project == ''  %]
                {
                    field: '[%- project_name -%]_[%- field.fieldname -%]_[%- field.dropfield -%]',
                    header: this.translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- project_name -%]_[%- field.fieldname -%]_[%- field.dropfield -%]'),
                    order: [% loop.count %],
                    datatype: 'text',
                    datatype_org: '[% field.datatype %]',
                    import_field: '[%- field.fieldname -%]'
                }[% "," IF loop.last() == 0 -%]
            [%- ELSIF field.foreign_key && field.visible && field.dropfield && field.project != ''  %]
                 {
                    field: '[%- field.project -%]_[%- field.fieldname -%]_[%- field.dropfield -%]',
                    header: this.translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.project -%]_[%- field.fieldname -%]_[%- field.dropfield -%]'),
                    order: [% loop.count %],
                    datatype: 'text',
                    datatype_org: '[% field.datatype %]',
                    import_field: '[%- field.fieldname -%]'
                }[% "," IF loop.last() == 0 -%]
            [% ELSIF field.foreign_key == 0 %]
                {
                    field: '[%- field.fieldname -%]',
                    header: this.translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.fieldname -%]'),
                    order: [% loop.count %],
                    datatype: '[% set_filter_type(col.datatype) %]',
                    datatype_org: '[% field.datatype %]',
                    import_field: '[%- field.fieldname -%]'
                }[% "," IF loop.last() == 0 -%]
            [%- END %]
        [%- END %]
        ];

    }
}

@@ component_html
<!-- Autogenerated file [%- date_time %] -->
<div>
    <div class="card">
        <p-toolbar styleClass="mb-6">
            <ng-template #start>
                <p-button label="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Button', 'New') }}" icon="pi pi-plus" severity="secondary" class="mr-2" (onClick)="openNew()" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'create')" />
                <p-button severity="secondary" label="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Button', 'Delete') }}" icon="pi pi-trash" (onClick)="confirmDeleteSelectedLines()" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'delete')" />
            </ng-template>

            <ng-template #end>
                <p-multiselect (onChange)="visibleColsChange($event)" (onSelectAllChange)="visibleColsAllChange($event)" display="chip" [options]="cols" [(ngModel)]="selectedColumns" optionLabel="header" selectedItemsLabel="{0} columns selected" [style]="{ 'min-width': '200px' }" class="mr-2" placeholder="Choose Columns" />
                <p-button label="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Button', 'Import') }}" icon="pi pi-download" severity="secondary" class="mr-2" (onClick)="showImportData()" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'import')" />
                <p-button label="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Button', 'Export') }}" icon="pi pi-upload" severity="secondary" class="mr-2" (onClick)="exportCSV()" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'export')" />
                <p-button icon="pi pi-cog" severity="secondary" (onClick)="userConfig('[%- project_name -%]', '[%- table.table_name -%]','Table')" />
            </ng-template>
        </p-toolbar>


    <p-table
            #dt
            [value]="payload_list"
            [rows]="10"
            [columns]="selectedColumns"
            [paginator]="true"
            stripedRows
            [loading]="tableLoading()"
            [globalFilterFields]="[
                [%- FOREACH field IN fields -%]
                    [%- IF field.foreign_key && field.visible && field.dropfield && field.project == '' -%]
'[%- project_name -%]_[%- field.fieldname -%]_[%- field.dropfield -%]',
                    [%- ELSIF field.foreign_key && field.visible && field.dropfield && field.project != '' -%]
'[%- field.project  -%]_[%- field.fieldname -%]_[%- field.dropfield -%]',
                    [%- ELSIF !field.foreign_key && field.visible -%]
'[%- field.fieldname -%]',
                    [%- END -%]
                [%- END -%]
]"
            [filterDelay]="0"
            [tableStyle]="{ 'min-width': '75rem' }"
            [(selection)]="selectedPayloads"
            [rowHover]="true"
            dataKey="[%- project_name -%]_[% table.table_name %]_pkey"
            currentPageReportTemplate="Showing {first} to {last} of {totalRecords} {{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- table.table_name -%]') }}"
            [showCurrentPageReport]="true"
            [rowsPerPageOptions]="[10, 20, 30]"
            columnResizeMode="expand"
            [showGridlines]="true"
            [resizableColumns]="true"
            [reorderableColumns]="true"
            (onColReorder)="reorderColumns($event)"
            (onColResize)="resizeColumns($event)"
            stateStorage="local"
            stateKey="[%- project_name -%]-[% table.table_name %]"
        >
            <ng-template #caption>
                <div class="flex items-center justify-between">
                    <h5 class="m-0">{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- table.table_name -%]') }}</h5>
                    <p-iconfield>
                        <p-inputicon class="pi pi-search" />
                        <input pInputText type="text" (input)="onGlobalFilter(dt, $event)" placeholder="Search..." />
                    </p-iconfield>
                </div>
            </ng-template>
            <ng-template #header let-columns >
                <tr>
                    <th style="width: 3rem">
                        <p-tableHeaderCheckbox />
                    </th>
                    @for (col of columns; track col) {
                        <th pSortableColumn="{{ col.field }}"  pResizableColumn pReorderableColumn >
                            {{ col.header }}
                            <p-sortIcon field="{{ col.field }}" />
                        </th>
                    }
                    <th style="min-width: 12rem"></th>
                  </tr>
            </ng-template>
            <ng-template #body let-payload_detail let-columns="columns">
                <tr>
                    <td style="width: 3rem">
                        <p-tableCheckbox [value]="payload_detail" />
                    </td>
                        @for (col of columns; track col) {
                            <td>
                                @if(col.datatype_org == 'BOOLEAN') {
                                    <p-tag [value]="getToggleText(payload_detail[col.field] )" [severity]="getToggle(payload_detail[col.field])" />
                                } @else {
                                    {{ payload_detail[col.field] }}
                                }
                            </td>
                        }
                     <p-button icon="pi pi-pencil" class="mx-2" [rounded]="true" [outlined]="true" (onClick)="editSelected(payload_detail)" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'update')" />
                     <p-button icon="pi pi-trash" severity="danger" [rounded]="true" [outlined]="true" (onClick)="confirmDeleteSelected(payload_detail)" [disabled]="!has_authority('[%- project_name -%]', '[%- table.table_name -%]', 'delete')"/>
                </tr>
            </ng-template>
        </p-table>
    </div>

        <p-dialog [(visible)]="detailDialog" [style]="{ width: '450px' }" header="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- table.table_name -%]') }} Details" [modal]="true">
        <ng-template #content>
            <div class="mt-6">
                <div class="flex flex-col gap-6">
                    [%- FOREACH field IN fields -%]
                        [% IF field.datatype == 'BOOLEAN' %]
                        <div class="flex gap-4 mt-1 p-3">
                            <p-checkbox inputId="[%- field.fieldname %]" name="[%- field.fieldname %]" value="true" [(ngModel)]="payload().[%- field.fieldname %]" [binary]="true" pTooltip="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Tooltip', '[%- field.fieldname -%]') }}" />
                            <label for="[%- field.fieldname %]" class="block font-bold ml-2">{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.fieldname -%]') }}</label>
                        </div>
                        [% ELSIF (field.datatype == 'BIGINT' || field.datatype == 'NUMERIC' || field.datatype == 'MONEY') && field.foreign_key == 0 %]
                        <div class="w-full">
                            <label for="[%- field.fieldname %]" class="block font-bold mb-3">{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.fieldname -%]') }}</label>
                            <p-inputnumber fluid inputId="[%- field.fieldname %]" [(ngModel)]="payload().[%- field.fieldname %]" pTooltip="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Tooltip', '[%- field.fieldname -%]') }}" />
                        </div>
                        [% ELSIF field.datatype == 'DATE' || field.datatype == 'TIMESTAMP' %]
                        <div>
                            <label for="[%- field.fieldname %]" class="block font-bold mb-3">{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.fieldname -%]') }}</label>
                            <p-datepicker fluid [(ngModel)]="payload().[%- field.fieldname %]" inputId="[%- field.fieldname %]" [showIcon]="true" dateFormat="yy-mm-dd"[showOnFocus]="false"/>
                        </div>
                        [%- ELSIF field.foreign_key && field.visible && field.project == '' %]
                            <p-select [options]="[%- project_name -%]_[%- field.fieldname -%]_list" [(ngModel)]="selected_[%- project_name -%]_[%- field.fieldname -%]" [checkmark]="true" optionLabel="[%- field.dropfield -%]" [showClear]="true" placeholder="Select [%- field.dropfield -%]" class="w-full font-bold md:w-56" />
                        [%- ELSIF field.foreign_key && field.visible && field.project != '' %]
                            <p-select [options]="[%- field.project -%]_[%- field.fieldname -%]_list" [(ngModel)]="selected_[%- field.project -%]_[%- field.fieldname -%]" [checkmark]="true" optionLabel="[%- field.dropfield -%]" [showClear]="true" placeholder="Select [%- field.dropfield -%]" class="w-full font-bold md:w-56" />
                        [%- ELSIF field.foreign_key == 0 %]
                            <div class="w-full">
                                    <label for="[%- field.fieldname %]" class="block font-bold mb-3">{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Label', '[%- field.fieldname -%]') }}</label>
                                    <input type="text" fluid pInputText id="[%- field.fieldname %]" [(ngModel)]="payload().[%- field.fieldname %]" [%- "required autofocus" IF field.mandatory -%] pTooltip="{{ translations.get_translation('[%- project_name -%]', '[%- table.table_name -%]', 'Tooltip', '[%- field.fieldname -%]') }}"  />
                            </div>
                        [%- END %]
                    [%- END %]
                </div>
            </div>
        </ng-template>

        <ng-template #footer>
            <p-button label="Cancel" icon="pi pi-times" text (onClick)="hideDialog()" />
            <p-button label="Save" icon="pi pi-check" (onClick)="saveObject()" />
        </ng-template>
        </p-dialog>
            <p-dialog [(visible)]="deleteDialog" [style]="{ width: '450px' }" header="Confirm" [modal]="true">
            <div class="flex items-center gap-4">
                <i class="pi pi-exclamation-triangle !text-3xl"></i>
                 @if (payload()) {
                    <span> Are you sure you want to delete selected item
[%- FOREACH field IN fields -%]
    [%- IF field.unique -%]
                        <b>{{ payload().[%- field.fieldname -%] }}</b>
    [%- END -%]
[%- END %]
                    ?</span>
                }
            </div>
            <ng-template #footer>
                <p-button label="No" icon="pi pi-times" text (onClick)="deleteDialog.set(false)" />
                <p-button label="Yes" icon="pi pi-check" (onClick)="deleteSelected(payload())" />
            </ng-template>
        </p-dialog>

		<p-dialog [(visible)]="userSettingsDialog" [style]="{ width: '650px' }" header="{{ translations.get_translation('companies', 'companies', 'Label', 'companies') }} Configuration" [modal]="true">
            <ng-template #content>
                <div class="card flex flex-wrap justify-center gap-4">
                    <div class="mt-6">
                     <div class="flex items-center">
                        <p-checkbox inputId="config1" name="config" value="true" [(ngModel)]="userConfigData().paginator" />
                        <label for="config1" class="block font-bold ml-3"> paginator </label>
                    </div>
                    <div class="flex items-center">
                        <p-checkbox inputId="config2" name="config" value="true" [(ngModel)]="userConfigData().rowHover" />
                        <label for="config2" class="block font-bold ml-3"> rowHover </label>
                    </div>
                    <div class="flex items-center">
                        <p-checkbox inputId="config3" name="config" value="true" [(ngModel)]="userConfigData().showCurrentPageReport" />
                        <label for="config3" class="block font-bold ml-3"> showCurrentPageReport </label>
                    </div>
                    <div class="flex items-center">
                        <p-checkbox inputId="config4" name="config" value="true" [(ngModel)]="userConfigData().showGridlines" />
                        <label for="config4" class="block font-bold ml-3"> showGridlines </label>
                    </div>

                    </div>
                </div>
            </ng-template>
            <ng-template #footer>
                <p-button label="Cancel" icon="pi pi-times" text (onClick)="hideUserSettingsDialog()" />
                <p-button label="Save" icon="pi pi-check" (onClick)="saveUserSettingsObject()" />
            </ng-template>
        </p-dialog>

@@ css

/* [%- table.table_name -%].component.css */

@@ the_end

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Templates::Tools::Generate::Angular; - It creates Angular code



=head1 SYNOPSIS


    use Daje::Templates::Tools::Generate::Angular;

    Provides a method for the template to be loaded into the data structure

    sub length_default_calc($self) returns a sub for setting details in template.




=head1 DESCRIPTION


Daje::Templates::Tools::Generate::Angular; is a module that retrieves data from a View



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 set_subs($self)

 set_subs($self)();


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

