package Daje::Document::Templates::Tools::Generate::Angular;
use Mojo::Base 'Daje::Document::Templates::Base', -base;
use v5.42;

# NAME
# ====
#
# Daje::Templates::Tools::Generate::Angular; - It creates Angular code
#
# SYNOPSIS
# ========
#
#     use Daje::Templates::Tools::Generate::Angular;
#
#     Provides a method for the template to be loaded into the data structure
#
#     sub length_default_calc($self) returns a sub for setting details in template.
#
#
# DESCRIPTION
# ===========
#
# Daje::Templates::Tools::Generate::Angular; is a module that retrieves data from a View
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

my $set_datatype = sub {
    my $datatype = $_[0];
    my $result = "string";
    if (uc($datatype) eq 'BIGINT') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'NUMERIC') {
        $result = 'numeric';
    }
    elsif (uc($datatype) eq 'BOOLEAN') {
        $result = 'boolean';
    }
    elsif (uc($datatype) eq 'MONEY') {
        $result = 'numeric';
    }

    return $result;
};

my $make_interface_name = sub {
    my $project = $_[0];
    my $table = $_[1];
    return ucfirst($project) . ucfirst($table) . "Interface";
};

sub set_subs($self) {
    $self->insert_sub('set_datatype', $set_datatype);
    $self->insert_sub('make_interface_name', $make_interface_name);
}

1;

__DATA__

@@ interface
// Autogenerated file [%- date_time %]
import{ ResponseBase } from 'daje-database';

export interface [%- class_name -%]Interface extends ResponseBase {
    [% project_name -%]_[%- table.table_name -%]_pkey:number,
    [%- FOREACH field IN fields -%]
    [%- IF field.foreign_key %]
    [% project_name -%]_[%- field.fieldname %]_fkey:number[% "," IF loop.last() == 0 %]
    [%- ELSE %]
    [% field.fieldname %]:[% set_datatype(field.datatype) %][% "," IF loop.last() == 0 %]
    [%- END -%]
    [% END %]
}

@@ component

// Autogenerated file [%- date_time %]
import {Component, OnInit, signal, ViewChild} from '@angular/core';
import {ConfirmationService, MessageService} from 'primeng/api';
import {Table, TableModule} from 'primeng/table';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ButtonModule} from 'primeng/button';
import {RippleModule} from 'primeng/ripple';
import {ToastModule} from[% project_name -%]_[%- field.fieldname -%]_list: 'primeng/toast';
import {ToolbarModule} from 'primeng/toolbar';
import {RatingModule} from 'primeng/rating';
import {InputTextModule} from 'primeng/inputtext';
import {TextareaModule} from 'primeng/textarea';
import {SelectModule} from 'primeng/select';
import {RadioButtonModule} from 'primeng/radiobutton';
import {InputNumberModule} from 'primeng/inputnumber';
import {DialogModule} from 'primeng/dialog';
import {TagModule} from 'primeng/tag';
import {InputIconModule} from 'primeng/inputicon';
import {IconFieldModule} from 'primeng/iconfield';
import { WorkflowService } from 'daje-workflow';
import { DatabaseService } from 'daje-database';
import { CheckboxModule } from 'primeng/checkbox';
import { [%- class_name -%]Interface } from './[%- table.table_name -%].interface'
[%- FOREACH field IN fields -%]
        [%- IF field.foreign_key && field.visible %]
import { [%- make_interface_name(project_name, field.fieldname) -%] } from './[%- field.fieldname -%].interface';
        [%- END -%]
    [% END %]

@Component({
  selector: 'p-[% project_name -%]-[%- table.table_name -%]',
  imports: [
        CommonModule,
        TableModule,
        FormsModule,
        ButtonModule,
        RippleModule,
        ToastModule,
        ToolbarModule,
        RatingModule,
        InputTextModule,
        TextareaModule,
        SelectModule,
        RadioButtonModule,
        InputNumberModule,
        DialogModule,
        TagModule,
        InputIconModule,
        IconFieldModule,
        CheckboxModule
  ],
  templateUrl: './[%table.table_name%].component.html',
  styleUrl: './[%table.table_name%].component.css',
  standalone: true,
})

export class [%- class_name -%]Component {
    detailDialog: boolean = false;
    payload:[%- class_name -%]Interface = {} as [%- class_name -%]Interface;
    selectedProducts:string = "";
    submitted:boolean = false;
    [%- FOREACH field IN fields -%]
        [%- IF field.foreign_key && field.visible %]
    selected_[%- field.dropfield -%]: string = "";

    [% project_name -%]_[%- field.fieldname -%]_list: [% make_interface_name(project_name, field.fieldname) %] ;
        [%- END -%]
    [% END %]

    constructor(
        private workflow: WorkflowService,
        private database: DatabaseService,
    ) {}

    saveObject() {

    }

    cancelData() {

    }
    openNew() {
        this.payload = {}  as [%- class_name -%]Interface;
        this.submitted = false;
        this.detailDialog = true;
    }
    exportCSV() {}
    confirmDeleteSelected(){}
    hideDialog(){this.detailDialog = false;}
}

@@ component_html
<!-- Autogenerated file [%- date_time %] -->
<div>
    <div class="card">
        <p-toolbar styleClass="mb-6">
            <ng-template #start>
                <p-button label="New" icon="pi pi-plus" severity="secondary" class="mr-2" (onClick)="openNew()" />
                <p-button severity="secondary" label="Delete" icon="pi pi-trash" (onClick)="confirmDeleteSelected()" [disabled]="!selectedProducts || !selectedProducts.length" />
            </ng-template>

            <ng-template #end>
                <p-button label="Export" icon="pi pi-upload" severity="secondary" (onClick)="exportCSV()" />
            </ng-template>
        </p-toolbar>
    </div>
        <p-dialog [(visible)]="detailDialog" [style]="{ width: '450px' }" header="Product Details" [modal]="true">
        <ng-template #content>
            <div class="flex flex-col gap-6">
                [%- FOREACH field IN fields -%]
                    [% IF field.datatype == 'BOOLEAN' %]
                    <div>
                        <label for="[%- field.fieldname %]" class="block font-bold mb-3">[%- field.fieldname %]</label>
                            <p-checkbox inputId="[%- field.fieldname %]" name="[%- field.fieldname %]" value="true" [(ngModel)]="payload.[%- field.fieldname %]" [binary]="true"/>
                        </div>
                    [%- ELSIF field.foreign_key && field.visible %]
                        <p-select [options]="[%- project_name -%]_[%- field.fieldname -%]_list" [(ngModel)]="selected_[%- field.dropfield -%]" [checkmark]="true" optionLabel="[%- field.dropfield -%]" [showClear]="true" placeholder="Select [%- field.dropfield -%]" class="w-full md:w-56" />
                    [%- ELSIF field.foreign_key == false -%]
                        <div>
                            <label for="[%- field.fieldname %]" class="block font-bold mb-3">[%- field.fieldname %]</label>
                            <input type="text" pInputText id="[%- field.fieldname %]" [(ngModel)]="payload.[%- field.fieldname %]" [%- "required autofocus fluid" IF field.mandatory -%] />
                            <small class="text-red-500" if@ (submitted && !payload.[%- field.fieldname %]) >[%- field.fieldname -%] is required.</small>
                        </div>
                    [%- END %]
                [%- END %]
            </div>
        </ng-template>
        <ng-template #footer>
            <p-button label="Cancel" icon="pi pi-times" text (onClick)="hideDialog()" />
            <p-button label="Save" icon="pi pi-check" (onClick)="saveObject()" />
        </ng-template>
    </p-dialog>
</div>
@@ css

/* [%- table.table_name -%].component.css */