package Daje::Document::Templates::Tools::Generate::Perl;
use Mojo::Base 'Daje::Document::Templates::Base', -base;
use v5.42;

# NAME
# ====
#
# Daje::Templates::Tools::Generate::Perl; - It creates perl code
#
# SYNOPSIS
# ========
#
#     use Daje::Templates::Tools::Generate::Perl;
#
#     Provides a method for the template to be loaded into the data structure
#
#     sub length_default_calc($self) returns a sub for setting details in template.
#
#
# DESCRIPTION
# ===========
#
# Daje::Templates::Tools::Generate::Perl; is a module that retrieves data from a View
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

sub set_subs($self) {
    #$self->subs('');
}

1;

__DATA__
@@ tests_controller

use v5.42;
use strict;
use Test::More 0.98;

# <!-- Autogenerated file [%- date_time %] -->

use_ok $_ for qw(
    Daje::Controller::[%- project -%]::[% class_name %]
);

done_testing;
1;

@@ tests_database_model

use v5.42;
use strict;
use Test::More 0.98;

# <!-- Autogenerated file [%- date_time %] -->

use_ok $_ for qw(
    Daje::Database::Model::[% class_name %]
);

done_testing;
1;

@@ controller_list

package Daje::Controller::[%- project -%]::[%- class_name %]List;
use Mojo::Base 'Daje::Controller::[%- project -%]::Super::[%- class_name -%]List', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::[%- class_name -%]List - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::[%- project -%]::[%- class_name %]List;
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::[%- project -%]::v[%- class_name -%]List is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

1;

@@ controller

package Daje::Controller::[%- project -%]::[%- class_name %];
use Mojo::Base 'Daje::Controller::[%- project -%]::Super::[%- class_name -%]', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::[%- project -%]::[%- class_name -%] - Controller class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::[%- project -%]::[%- class_name %]
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::[%- project -%]::[%- class_name -%] is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

1;

@@ super_controller_list

package Daje::Controller::[%- project -%]::Super::[%- class_name %]List;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::[%- project -%]::Super::[%- class_name -%]List - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::[%- project -%]::Super::v[%- class_name -%]
#
       [%- FOREACH table IN tables %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]/:[%- project_name -%]_[%- table.table_name %]_pkey');
       [%- FOREACH field IN table.fields %]
       [%- IF field.foreign_key %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]_[%- field.fieldname -%]/:[%- project_name -%]_[%- field.fieldname %]_fkey');

       [% END %]
       [%- END -%]
       [%- END -%]
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::[%- project -%]::Super::[%- class_name -%] is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

sub load_all_[%- project_name -%]_[%- table.table_name -%]($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]List::load_all_[%- project_name -%]_[%- table.table_name -%] ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- project_name -%]_[% table.table_name %]_list->load_all_[%- project_name -%]_[%- table.table_name -%]_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]List::load_all_[%- project_name -%]_[%- table.table_name -%] ' . $err);
        $self->render
    });
}

[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' -%]
sub load_list_[%- project_name -%]_[%- field.fieldname -%]_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]List::load_list[%- project_name -%]_[%- field.fieldname -%]_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('[%- project_name -%]_[%- field.fieldname -%]_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- project_name -%]_[% tablename %]_list->[%- project_name -%]_[%- field.fieldname -%]_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]::load_[%- project_name -%]_[%- field.fieldname -%]_fkey ' . $err);
        $self->render
    });
}
[%- ELSIF field.foreign_key && field.project != '' -%]
sub load_list_[%- field.project  -%]_[%- field.fieldname -%]_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]List::load_list[%- field.project  -%]_[%- field.fieldname -%]_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('[%- field.project  -%]_[%- field.fieldname -%]_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- field.project  -%]_[% tablename %]_list->[%- field.project  -%]_[%- field.fieldname -%]_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]::load_[%- field.project  -%]_[%- field.fieldname -%]_fkey ' . $err);
        $self->render
    });
}
[%- END -%]
[%- END -%]

1;

@@ super_controller

package Daje::Controller::[%- project -%]::Super::[%- class_name %];
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::[%- project -%]::[%- class_name -%] - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::[%- project -%]::Super::v[%- class_name -%]
#
       [%- FOREACH table IN tables %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]/:[%- project_name -%]_[%- table.table_name %]_pkey');
       [%- FOREACH field IN table.fields %]
       [%- IF field.foreign_key %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]_[%- field.fieldname -%]/:[%- project_name -%]_[%- field.fieldname %]_fkey');

       [% END %]
       [%- END -%]
       [%- END -%]
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::[%- project -%]::Super::[%- class_name -%] is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

sub load_[%- project_name -%]_[%- table.table_name -%]_pkey($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]::load_[%- project_name -%]_[%- field.fieldname -%]_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $pkey = $self->param('[%- project_name -%]_[%- table.table_name -%]_pkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- project_name -%]_[% table.table_name %]->load_[%- project_name -%]_[%- table.table_name -%]_pkey_p($pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]::load_[%- project_name -%]_[%- table.table_name -%]_pkey ' . $err);
        $self->render
    });
}

[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' -%]
sub load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]::load_[%- project_name -%]_[%- field.fieldname -%]_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('[%- project_name -%]_[%- field.fieldname -%]_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- project_name -%]_[% tablename %]->[%- project_name -%]_[%- field.fieldname -%]_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]::load_[%- project_name -%]_[%- field.fieldname -%]_fkey ' . $err);
        $self->render
    });
}
[%- ELSIF field.foreign_key && field.project != '' -%]
sub load_[%- field.project  -%]_[%- field.fieldname -%]_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::[%- class_name -%]::load_[%- field.project  -%]_[%- field.fieldname -%]_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('[%- field.project  -%]_[%- field.fieldname -%]_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_[%- field.project  -%]_[% tablename %]->[%- field.project  -%]_[%- field.fieldname -%]_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::[%- class_name -%]::load_[%- field.project  -%]_[%- field.fieldname -%]_fkey ' . $err);
        $self->render
    });
}
[%- END -%]
[%- END -%]

1;

@@ helpers

package Daje::Plugin::[%- class_name -%]::Helpers;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::[%- class_name -%]::Helpers - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::[%- class_name -%]::Helpers;
#
#       my $class = Daje::Plugin::[%- class_name -%]::Helpers->new();
[%- FOREACH table IN tables %]
#       $app->helper(
#           v_[% project_name %]_[% table.table_name %] => sub {
#               state  $v_[% project_name %]_[% table.table_name %] = Daje::Database::Model::v[%- table.class_name -%]->new(db => shift->pg->db)
#        });
[%- END -%]
#
[%- FOREACH table IN tables %]
#       $app->helper(
#           v_[% project_name %]_[% table.table_name %]_list => sub {
#               state  $v_[% project_name %]_[% table.table_name %]_list = Daje::Database::Model::v[%- table.class_name -%]List->new(db => shift->pg->db)
#        });
[%- END -%]
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::[%- class_name -%]::Helpers is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

    [%- FOREACH table IN tables %]
use Daje::Database::View::v[%- table.class_name -%];
    [%- END -%]
# Lists
    [%- FOREACH table IN tables %]
use Daje::Database::View::v[%- table.class_name -%]List;
    [%- END %]

our $VERSION = '0.01';

sub helpers($self, $app, $config) {

    [%- FOREACH table IN tables %]
    $app->helper(
        v_[% project_name %]_[% table.table_name %] => sub {
            state  $v_[% project_name %]_[% table.table_name %] = Daje::Database::View::v[%- table.class_name -%]->new(db => shift->pg->db)
        });
    [%- END -%]
    # Lists
    [%- FOREACH table IN tables %]
    $app->helper(
        v_[% project_name %]_[% table.table_name %]_list => sub {
            state  $v_[% project_name %]_[% table.table_name %]_list = Daje::Database::View::v[%- table.class_name -%]List->new(db => shift->pg->db)
        });
    [%- END -%]
}

1;



@@ routes

package Daje::Plugin::[%- class_name -%]::Routes;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::[%- class_name -%]::Routes - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::[%- class_name -%]::Routes;
#
#       my $class = Daje::Plugin::[%- class_name -%]::Routes->new();
       [%- FOREACH table IN tables %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]/:[%- project_name -%]_[%- table.table_name %]_pkey');
       [%- FOREACH field IN table.fields %]
       [%- IF field.foreign_key %]
#       $r->get('/[%- project_name -%]/api/v1/[%- table.table_name -%]_[%- field.fieldname -%]/:[%- project_name -%]_[%- field.fieldname %]_fkey');

       [% END %]
       [%- END -%]
       [%- END -%]
#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::[%- class_name -%]::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

sub routes($self, $app, $config) {
    my $r = $app->auth;

    [%- FOREACH table IN tables %]
    $r->get('v1/[%- table.table_name -%]_list_all/')->to('[%- table.class_name -%]List#load_all_[%- project_name -%]_[%- table.table_name -%]');
    [%- FOREACH field IN table.fields %]
    [%- IF field.foreign_key && field.project == '' %]
    $r->get('v1/[%- table.table_name -%]_[%- field.fieldname -%]_list/:[%- project_name -%]_[%- field.fieldname -%]_fkey')->to('[%- table.class_name -%]#load_list_[%- project_name -%]_[%- field.fieldname -%]_fkey');
    [%- ELSIF field.foreign_key && field.project != '' %]
    $r->get('v1/[%- table.table_name -%]_[%- field.fieldname -%]_list/:[%- field.project -%]_[%- field.fieldname -%]_fkey')->to('[%- table.class_name -%]#load_list_[%- field.project -%]_[%- field.fieldname -%]_fkey');
    [%- END -%]
    [%- END -%]
    [%- END %]

[%- FOREACH table IN tables %]
    [%- FOREACH field IN table.fields %]
    [%- IF field.foreign_key %]
    $r->get('v1/[%- table.table_name -%]_[%- field.fieldname -%]/:[%- project_name -%]_[%- field.fieldname -%]_fkey')->to('[%- table.class_name -%]#load_[%- project_name -%]_[%- field.fieldname -%]_fkey');
    [%- END -%]
    [%- END -%]
    $r->get('v1/[%- table.table_name -%]/:[%- project_name -%]_[%- table.table_name -%]_pkey')->to('[%- table.class_name -%]#load_[%- project_name -%]_[%- table.table_name -%]_pkey');
[%- END %]
}

@@ languages

package Daje::Plugin::[%- class_name -%]::Languages;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::[%- class_name -%]::Languages - Model class
#
# SYNOPSIS
# ========
#
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::[%- class_name -%]::Languages is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

use Daje::Helper::Languages::InsertKeys;

has 'db';

sub language($self) {

    try {
        my $tx = $self->db->begin;
        my @keys;
[%- FOREACH table IN tables %]
        push @keys, {
                plugin => "[%- project_name -%]",
                key => "[% table.table_name %]",
                field => "table",
                type => "Label",
                translation => "[% table.label %]",
                comment => "[% table.comment %]",
            };
        [%- FOREACH field IN table.fields %]
          push @keys,  {
                plugin => "[%- project_name -%]",
                key => "[% table.table_name %]",
                field => "[% field.fieldname %]",
                type => "Label",
                translation => "[% field.label %]",
                comment => "[% field.comment %]"
            };
           push @keys, {
                plugin => "[%- project_name -%]",
                key => "[% table.table_name %]",
                field => "[% field.fieldname %]",
                type => "Tool tips",
                translation => "[% field.tooltip %]",
                comment => "[% field.comment %]"
            };
         [% END -%]
 [%- END %]

        Daje::Helper::Languages::InsertKeys->new(
            db => $self->db
        )->process(
             \@keys
        );
        $tx->commit();
    } catch($e) {
        say $e;
    }
}

1;


@@ authorities

package Daje::Plugin::[%- class_name -%]::Authorities;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::[%- class_name -%]::Authorities - Model class
#
# SYNOPSIS
# ========
#
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::[%- class_name -%]::Authorities is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be generated by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->

use Daje::Helper::Authorities::InsertPluginFunction;

has 'db';

sub authorize($self) {

    try {
        my $tx = $self->db->begin;
        my @functions = (
    [%- FOREACH table IN tables %]
            "[%- project_name -%]_[%- table.table_name %]"[% "," IF loop.last() == 0 %]
    [%- END %]
        );

        Daje::Helper::Authorities::InsertPluginFunction->new(
            db => $self->db
        )->process(
            "[%- project_name -%]", \@functions
        );
        $tx->commit();
    } catch($e) {
        say $e;
    }
}

1;

@@ db_view_list

package Daje::Database::View::v[%- class_name -%]List;
use Mojo::Base 'Daje::Database::View::Super::v[%- class_name -%]List', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::v[%- class_name -%]List - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::v[%- class_name %]List;
#
#       my $class = Daje::Database::View::v[%- class_name -%]List->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::v[%- class_name -%]List is the List View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::v[%- class_name -%]List
#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools [% date_time %].
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->


our $VERSION = '0.01';

1;

@@ db_view

package Daje::Database::View::v[%- class_name -%];
use Mojo::Base 'Daje::Database::View::Super::v[%- class_name -%]', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::v[%- class_name -%] - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::v[%- class_name %];
#
#       my $class = Daje::Database::View::v[%- class_name -%]->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::v[%- class_name -%] is the View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::v[%- class_name -%]
#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools [% date_time %].
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->


our $VERSION = '0.01';

1;

@@ db_model

package Daje::Database::Model::[%- class_name -%];
use Mojo::Base 'Daje::Database::Model::Super::[%- class_name -%]', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::Model::[%- class_name -%] - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::Model::[%- class_name %];
#
#       my $class = Daje::Database::Model::[%- class_name -%]->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::[%- class_name -%] is the model
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::Model::Super::[%- class_name -%]
#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools [% date_time %].
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file [%- date_time %] -->


our $VERSION = '0.01';

1;

@@ db_view_super

package Daje::Database::View::Super::v[%- class_name -%];
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::v[%- class_name -%] - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::v[%- class_name -%];
#
#       my $table = Daje::Database::View::Super::v[%- class_name -%]->new(db => $db);
#
#       my $result = $table->load_[%- project_name -%]_[%- table.table_name -%]_pkey($self, $[%- project_name -%]_[%- table.table_name -%]_pkey);
#
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key %]
#       my $result = $table->load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey);
#
[%- END -%]
[%- END -%]
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::v[%- class_name -%] is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

has 'fields' => '"[%- project_name -%]_[%- table.table_name -%]_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' -%]
"[%- project_name -%]_[%- field.fieldname -%]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSIF field.foreign_key && field.project != '' -%]
"[%- field.project -%]_[%- field.fieldname -%]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSE -%]
"[%- field.fieldname %]"[% "," IF loop.last() == 0 %]
[%- END -%]
[%- END -%]';
has 'primary_key_name' => "[%- project_name -%]_[%- table.table_name -%]_pkey";
has 'table_name' => "v_[%- project_name -%]_[%- table.table_name -%]";


[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' %]
async sub load_[%- project_name -%]_[%- field.fieldname -%]_fkey_p($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_[%- project_name -%]_[%- field.fieldname -%]_fkey($[%- project_name -%]_[%- field.fieldname -%]_fkey);
}

sub load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "[%- project_name -%]_[%- field.fieldname -%]_fkey", $[%- project_name -%]_[%- field.fieldname -%]_fkey
    );
}
[%- ELSIF field.foreign_key && field.project != '' %]
async sub load_[%- field.project -%]_[%- field.fieldname -%]_fkey_p($self, $[%- field.project -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_[%- field.project -%]_[%- field.fieldname -%]_fkey($[%- field.project -%]_[%- field.fieldname -%]_fkey);
}

sub load_[%- field.project -%]_[%- field.fieldname -%]_fkey($self, $[%- field.project -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "[%- field.project -%]_[%- field.fieldname -%]_fkey", $[%- field.project -%]_[%- field.fieldname -%]_fkey
    );
}
[%- END -%]
[%- END -%]

async sub load_[%- project_name -%]_[%- table.table_name -%]_pkey_p($self, $[%- project_name -%]_[%- table.table_name -%]_pkey) {
    return $self->load_[%- project_name -%]_[%- table.table_name -%]_pkey($[%- project_name -%]_[%- table.table_name -%]_pkey);
}

sub load_[%- project_name -%]_[%- table.table_name -%]_pkey($self, $[%- project_name -%]_[%- table.table_name -%]_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $[%- project_name -%]_[%- table.table_name -%]_pkey
    );
}

1;

@@ db_view_super_list

package Daje::Database::View::Super::v[%- class_name -%]List;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::v[%- class_name -%]List - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::v[%- class_name -%]List;
#
#       my $table = Daje::Database::View::Super::v[%- class_name -%]List->new(db => $db);
#
#       my $result = $table->load_[%- project_name -%]_[%- table.table_name -%]_pkey($self, $[%- project_name -%]_[%- table.table_name -%]_pkey);
#
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key %]
#       my $result = $table->load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey);
#
[%- END -%]
[%- END -%]
#
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::[%- class_name -%]List is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

has 'fields' => '"[%- project_name -%]_[%- table.table_name -%]_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.visible && field.dropfield && field.project == '' -%]
[%- project_name -%]_[%- field.fieldname -%]_[%- field.dropfield %],
"[%- project_name -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSIF field.foreign_key && field.visible && field.dropfield && field.project != '' -%]
[%- field.project -%]_[%- field.fieldname -%]_[%- field.dropfield %],
"[%- field.project -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSIF field.foreign_key && field.project == '' %]
"[%- project_name -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSIF field.foreign_key && field.project != '' %]
"[%- field.project -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSE -%]
"[%- field.fieldname %]"[% "," IF loop.last() == 0 %]
[%- END -%]
[%- END -%]';
has 'primary_key_name' => "[%- project_name -%]_[%- table.table_name -%]_pkey";
has 'table_name' => "v_[%- project_name -%]_[%- table.table_name -%]_list";

[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' %]
async sub load_all_[%- project_name -%]_[%- field.fieldname -%]_list_p($self) {
    return $self->load_all_[%- project_name -%]_[%- field.fieldname -%]_list();
}

sub load_all_[%- project_name -%]_[%- field.fieldname -%]_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_[%- project_name -%]_[%- field.fieldname -%]_list_p($self, $key_value) {
    return $self->load_[%- project_name -%]_[%- field.fieldname -%]_list($key_value);
}

sub load_[%- project_name -%]_[%- field.fieldname -%]_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
[%- ELSIF field.foreign_key && field.project != '' %]
async sub load_all_[%- field.project -%]_[%- field.fieldname -%]_list_p($self) {
    return $self->load_all_[%- field.project -%]_[%- field.fieldname -%]_list();
}

sub load_all_[%- field.project -%]_[%- field.fieldname -%]_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_[%- field.project -%]_[%- field.fieldname -%]_list_p($self, $key_value) {
    return $self->load_[%- project_name -%]_[%- field.fieldname -%]_list($key_value);
}

sub load_[%- field.project -%]_[%- field.fieldname -%]_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
[%- END -%]
[%- END -%]

async sub load_all_[%- project_name -%]_[%- table.table_name -%]_p($self) {
    return $self->load_all_[%- project_name -%]_[%- table.table_name -%]();
}

sub load_all_[%- project_name -%]_[%- table.table_name -%]($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;


@@ db_model_super

package Daje::Database::Model::Super::[%- class_name -%];
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::Model::Super::[%- class_name -%] - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::Model::Super::[%- class_name -%];
#
#       my $table = Daje::Database::Model::Super::[%- class_name -%]->new(db => $db);
#
#       my $result = $table->load_[%- project_name -%]_[%- table.table_name -%]_pkey($self, $[%- project_name -%]_[%- table.table_name -%]_pkey);
#
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key %]
#       my $result = $table->load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey);
#
[%- END -%]
[%- END -%]
#
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::Super::[%- class_name -%] is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools [% date_time %].
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file [%- date_time %] -->

our $VERSION = '0.01';

has 'fields' => '"[%- project_name -%]_[%- table.table_name -%]_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' %]
"[%- project_name -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSIF field.foreign_key && field.project != '' %]
"[%- field.project -%]_[%- field.fieldname %]_fkey"[% "," IF loop.last() == 0 %]
[%- ELSE -%]
"[%- field.fieldname %]"[% "," IF loop.last() == 0 %]
[%- END -%]
[%- END -%]';
has 'primary_key_name' => "[%- project_name -%]_[%- table.table_name -%]_pkey";
has 'table_name' => "[%- project_name -%]_[%- table.table_name -%]"; # [% comment %]
has 'mandatory' => '[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.mandatory && field.project == '' -%]
[%- project_name -%]_[%- field.fieldname -%]_fkey,
[%- ELSIF field.foreign_key && field.mandatory && field.project != '' -%]
[%- field.project -%]_[%- field.fieldname -%]_fkey,
[%- ELSIF field.mandatory -%]
[%- field.fieldname -%],
[%- END -%]
[%- END -%]';
has 'workflow' => '[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.fieldname == 'workflow' && field.mandatory -%]
[%- project_name -%]_[%- field.fieldname -%]_fkey
[%- END -%]
[%- END -%]';

[%- FOREACH field IN fields -%]
[%- IF field.foreign_key && field.project == '' %]
async sub load_[%- project_name -%]_[%- field.fieldname -%]_fkey_p($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_[%- project_name -%]_[%- field.fieldname -%]_fkey($[%- project_name -%]_[%- field.fieldname -%]_fkey);
}

sub load_[%- project_name -%]_[%- field.fieldname -%]_fkey($self, $[%- project_name -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "[%- project_name -%]_[%- field.fieldname -%]_fkey", $[%- project_name -%]_[%- field.fieldname -%]_fkey
    );
}
[%- ELSIF field.foreign_key && field.project != '' %]
async sub load_[%- field.project -%]_[%- field.fieldname -%]_fkey_p($self, $[%- field.project -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_[%- field.project -%]_[%- field.fieldname -%]_fkey($[%- field.project -%]_[%- field.fieldname -%]_fkey);
}

sub load_[%- field.project -%]_[%- field.fieldname -%]_fkey($self, $[%- field.project -%]_[%- field.fieldname -%]_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "[%- field.project  -%]_[%- field.fieldname -%]_fkey", $[%- field.project  -%]_[%- field.fieldname -%]_fkey
    );
}
[%- END -%]
[%- END -%]

async sub load_[%- project_name -%]_[%- table.table_name -%]_pkey_p($self, $[%- project_name -%]_[%- table.table_name -%]_pkey) {
    return $self->load_[%- project_name -%]_[%- table.table_name -%]_pkey($[%- project_name -%]_[%- table.table_name -%]_pkey);
}

sub load_[%- project_name -%]_[%- table.table_name -%]_pkey($self, $[%- project_name -%]_[%- table.table_name -%]_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $[%- project_name -%]_[%- table.table_name -%]_pkey
    );
}

sub insert($self, $data) {
    my $result = $self->SUPER::insert(
        $self->table_name, $data, $self->primary_key_name
    );
    return $result;
}

sub update($self, $data) {
    return $self->SUPER::update
    (
        $self->table_name, $data,
            {
                $self->primary_key_name() => $data->{$self->primary_key_name()}
            }
    );
}

sub delete($self, $primary_key) {
    return $self->SUPER::delete($self->table_name, { $self->primary_key_name() => $primary_key});
}
1;

@@ plugin

package Daje::Plugin::[% plugin_name %];
use Mojo::Base 'Mojolicious::Plugin', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::[% plugin_name %] - Mojolicious Plugin
#
# SYNOPSIS
# ========
#
# Mojolicious
# ===========
#
#      $self->plugin('[% plugin_name %]');
#
# Mojolicious::Lite
# =================
#
#      plugin '[% plugin_name %]';
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::[% plugin_name %] is a Mojolicious plugin.
#
# METHODS
# =======
#
# Daje::Plugin::[% plugin_name %] inherits all methods from
# Mojolicious::Plugin and implements the following new ones.
#
# register
# ========
#  $plugin->register(Mojolicious->new);
#
# Register plugin in L<Mojolicious> application.
#
# SEE ALSO
# ========
#
# Mojolicious, Mojolicious::Guides, https://mojolicious.org.
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools [% date_time %].
# It will not be touched by Daje Tools again.

# <!-- Autogenerated file [%- date_time %] -->

use Daje::Plugin::[% plugin_name %]::Routes;
use Daje::Plugin::[% plugin_name %]::Helpers;
use Daje::Plugin::[% plugin_name %]::Authorities;
use  Daje::Database::Migrator;

our $VERSION = '0.01';

sub register ($self, $app, $config) {
    $app->log->debug("Daje::Plugin::[% plugin_name %]::register start");

    my $migration->{class} = 'Daje::Database::[% plugin_name %]';
    $migration->{name} = '[%- section_name -%]';
    $migration->{migration} = 1;
    my $migrations;
    push @{$migrations}, $migration;
    try {
        Daje::Database::Migrator->new(
            pg         => $app->pg,
            migrations => $migrations,
        )->migrate();
    } catch ($e) {
        $app->log->error($e);
    };

    Daje::Plugin::[% plugin_name %]::Routes->new()->routes($app, $config);
    Daje::Plugin::[% plugin_name %]::Helpers->new()->helpers($app, $config);
    Daje::Plugin::[% plugin_name %]::Authorities->new(db => $app->pg->db)->authorize();


    $app->log->debug("Daje::Plugin::[% plugin_name %]::register ends");
}

1;

@@ activity

package Daje::Workflow::Activities::[%- plugin_name -%]::Activity;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Workflow::Activities::[% plugin_name %]::Activity - A workflow activity
#
# SYNOPSIS
# ========
#;
#
# DESCRIPTION
# ===========
#
# Daje::Workflow::Activities::[% plugin_name %]::Activity is a Daje workflow activity.
#
# METHODS
# =======
#
# Daje::Workflow::Activities::[% plugin_name %]::Activity inherits all methods from
# Daje::Workflow::Activities::Tools::Generate::Base and implements the following new ones.
#
# activity
#
# SEE ALSO
# ========
#
# Mojolicious, Mojolicious::Guides, https://mojolicious.org.
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools [% date_time %].
# It will not be touched by Daje Tools again.

# <!-- Autogenerated file [%- date_time %] -->

sub activity($self) {


}

1;

@@ the_end

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Templates::Tools::Generate::Perl; - It creates perl code



=head1 SYNOPSIS


    use Daje::Templates::Tools::Generate::Perl;

    Provides a method for the template to be loaded into the data structure

    sub length_default_calc($self) returns a sub for setting details in template.




=head1 DESCRIPTION


Daje::Templates::Tools::Generate::Perl; is a module that retrieves data from a View



=head1 REQUIRES

L<Daje::Database::Migrator> 

L<Daje::Plugin::[%> 

L<Daje::Plugin::[%> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<Daje::Database::View::v[%-> 

L<Daje::Database::View::v[%-> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<v5.42> 

L<Mojo::Base> 

L<Test::More> 

L<v5.42> 

L<Test::More> 

L<v5.42> 

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 delete($self,

 delete($self,();

=head2 helpers($self,

 helpers($self,();

=head2 insert($self,

 insert($self,();

=head2 load_[%-

 load_[%-();

=head2 load_all_[%-

 load_all_[%-();

=head2 load_list_[%-

 load_list_[%-();

=head2 register

 register();

=head2 routes($self,

 routes($self,();

=head2 set_subs($self)

 set_subs($self)();

NAME
====

Daje::Templates::Tools::Generate::Perl; - It creates perl code

SYNOPSIS
========

    use Daje::Templates::Tools::Generate::Perl;

    Provides a method for the template to be loaded into the data structure

    sub length_default_calc($self) returns a sub for setting details in template.


DESCRIPTION
===========

Daje::Templates::Tools::Generate::Perl; is a module that retrieves data from a View

LICENSE
=======

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

AUTHOR
======

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head2 update($self,

 update($self,();


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

