package Daje::Database::Model::ToolsCodeChecksum;
use Mojo::Base 'Daje::Database::Model::Super::ToolsCodeChecksum', -base, -signatures, -async_await;;



1;

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::ToolsObjects


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS


=cut

