package Daje::Database::Model::Super::ToolsCodeChecksum;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;;
use v5.42;

has 'fields' => 'tools_code_checksum_pkey, editnum, insby, insdatetime, modby, moddatetime, tools_code_fkey, checksum';
has 'primary_key_name' => "tools_code_checksum_pkey";
has 'table_name' => "tools_code_checksum";
has 'workflow' => '';


sub load_tools_code_checksum_pkey($self, $tools_code_checksum_pkey_pkey) {

    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $tools_objects_pkey
    );
}

sub load_tools_code_checksum_fkey($self, $tools_code_fkey) {

    return $self->load_fkey(
        $self->table_name, $self->fields(), "tools_code_fkey", $tools_code_fkey
    );
}

sub insert($self, $data) {
    my $result = $self->SUPER::insert($self->table_name, $data, $self->primary_key_name);
    return $result;
}


sub update($self, $data) {
    return $self->SUPER::update($self->table_name, $data, { $self->primary_key_name() => $data->{$self->primary_key_name()}});
}

1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::Super::ToolsCode


=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS


=cut

