package Daje::Database::Model::Super::ToolsCode;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;;
use v5.42;

has 'fields' => 'tools_code_pkey, editnum, insby, insdatetime, modby, moddatetime, tools_objects_fkey, filename, filetype, content';
has 'primary_key_name' => "tools_code_pkey";
has 'table_name' => "tools_code";
has 'workflow' => '';


sub load_tools_code_pkey($self, $tools_code_pkey) {

    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $tools_code_pkey
    );
}

sub load_tools_code_fkey($self, $tools_object_pkey) {

    return $self->load_fkey(
        $self->table_name, $self->fields(), "tools_object_fkey", $tools_object_pkey
    );
}

sub load_tools_code_pkey_from_filename($self, $filename) {
    return $self->load_from_index(
        $self->table_name,
        $self->fields, {
            filename => $filename
        }
    );

}

sub insert($self, $data) {
    my $result = $self->SUPER::insert($self->table_name, $data, $self->primary_key_name);
    return $result;
}


sub update($self, $data) {
    return $self->SUPER::update($self->table_name, $data, { $self->primary_key_name() => $data->{$self->primary_key_name()}});
}

sub delete($self, $primary_key) {
    return $self->SUPER::delete($self->table_name, { $self->primary_key_name() => $primary_key});
}
1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::Super::ToolsCode


=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS


=cut

